spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  session:
    store-type: none
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.liaocc.demo.po
logging:
  level:
    root: info
    com.liaocc: debug

  file: log/blog-dev.log
server:
  port: 8081
  connection-timeout: 20000

